[INFO]
mod_author: Xx_Yubari_xX
mod_help: Spawns peds that ambiently wander around, and provides a few global functions to influence the spawning.
require_dependency: sync+
require_version: 12

[SCRIPTS]
main_script: sv_ambient.lua
client_script: cl_ambient.lua
client_file: population.lua		# check population.lua for advanced configuration

[PREFERENCES]
# maximum number spawnable by this script and the minimum amount of entity space to maintain
maximum_spawned: 100
minimum_space: 200

# peds only spawn if no player is in the minimum distance and at least one is in the maximum
spawn_dist_min: 25
spawn_dist_max: 45

# peds will not spawn if there are other sync entities within these distances
spawn_spacing_peds: 1.5
spawn_spacing_vehicles: 5

# a ped will despawn if no players are within its despawn distance
despawn_distance: 55

# distance used to count the population near a player (should be higher than despawn)
population_distance: 60

# peds will not spawn if there are this many peds within population distance
max_nearby_population: 20

# turn ambient spawning on in the main dimension by default
on_by_default: true