# derpy's script server: config
config_version 6


[SERVER]

# Basic server options.
server_name: Unconfigured Server
server_info: The owner of this server should probably edit dslconfig.ini.
server_players: 16

# Uncomment to specify an optional 1:1 png for the server icon.
#server_icon: icon.png

# Uncomment to supply server browsers with a link (for sign up or info).
#server_link: /signup.html

# Port number. If not 17017, clients will have to specify it when connecting.
server_port: 17017

# How many times the server should update in a second. Works best at 30 or 60.
server_hz: 30

# Use c-side sync for entities. It is heavily suggested you pair this with sync mod(s).
use_sync: true

# ** READ THE EULA BEFORE TURNING THIS ON (see eula.txt) **
read_eula: false


[ACCOUNT_CONFIG]

# Uncomment ssl_chain *or* ssl_cert, *and* ssl_key. Otherwise accounts will be disabled.
#ssl_chain: server-fullchain.pem
#ssl_cert: server-cert.pem
#ssl_key: server-key.pem

# Uncomment both to host a web api that can be used for account management (see manual.pdf).
#signup_ip: 127.0.0.1
#signup_port: 17018

# Maximum amount of accounts per IP per server reset (like /quit restart), use 0 to disable limit.
max_accounts_per_reset: 2

# If accounts are required to play on this server, otherwise "guests" can join without one.
account_only: false

# If the default username ("player") should be rejected, even as a guest username.
no_default_name: false

# List of possible account roles. Some mods require you add custom ones (each on their own line).
account_role: admin


[STARTUP_BEHAVIOR]

# Mods will start automatically if auto_start is enabled here *and* not disabled by the mod.
auto_start: true

# Uncomment to specify a file with commands to run after DSL starts. Use multiple lines for more files.
#cmd_file: commands.txt


[CONSOLE_PREFERENCES]

# Only disable if you don't want console output being logged, since each can take up to 2 MB.
console_logging: true

# Disable console input to slightly optimize the server if you won't be typing commands.
console_no_input: false


[BLACKLIST_AND_WHITELIST]

# If the whitelist should be used instead of a blacklist.
whitelist_instead: false

# Uncomment to specify an IP that can't connect. Use multiple lines for more IP addresses.
#blacklist_ip: 0.0.0.0

# Uncomment to specify an IP that can connect. Use multiple lines for more IP addresses.
#whitelist_ip: 0.0.0.0


[ADVANCED_SERVER_SETTINGS]

# Listening address (don't change unless you know what you're doing).
server_ip: 0.0.0.0

# Show warnings about server performance. Usually not recommended.
tick_warnings: false

# If game traffic should be encrypted instead of just the sign-in process.
encrypt_game: false

# Show when a client has been sent listing information.
show_listing: false

# Show a warning for the reason a player is about to be dropped because of errors.
show_player_errors: false

# Maximum amount of incoming scripted events per player (or use 0 for no limit).
event_rate_limit: 1000

# Limit connections from one IP address (or use 0 for no limit).
limit_per_ip: 0


[UNRESTRICTED_SYSTEM_ACCESS]
###########################################################################################
##                                                                                       ##
## ~~~~~ WARNING: THE SETTING BELOW GIVES *ALL* SCRIPTS FULL ACCESS TO YOUR SYSTEM ~~~~~ ##
## ~~~ Only turn on if you trust all your mods are safe! I'm not liable for damages! ~~~ ##
##                                                                                       ##
###########################################################################################
allow_system_access: false