# SYNC+ | config | Xx_Yubari_xX

[INFO]
mod_author: Xx_Yubari_xX
mod_help: Sync+ provides fundamental sync on top of the core entity sync provided by DSL / DSS.
require_name: sync+
require_version: 12
require_sync: true

[AUTHORITY]
server_stats: true			# only allow the server to decide ped stats
server_max_hp: true			# only allow the server to decide max health
server_dmg_mult: true		# only allow the server to decide damage multipliers
server_gravity: false		# only allow the server to decide if gravity is enabled
server_inf_sprint: false	# only allow the server to decide if infinite sprint is on

[PREFERENCES]
correct_node_delay: 1000	# ms before a wrong action on an unowned ped is corrected
inf_player_sprint: false	# if players should have infinite sprint by default
force_player_ai: true		# ensure players always have PlayerAI and that non-players don't
allow_double_hp: false		# allow players to have double max hp
weather_trans_ms: 1800		# how long it takes two weather types to blend together
weapon_rate_limit: 30		# weapon setting is rate limited to prevent crashes
weapon_rate_timer: 2000

[DEFAULTS]
default_clock_hour: 8		# default game hour
default_clock_minutes: 0	# default game minute
default_clock_rate: 60		# game seconds per real second

[UTILITY_SCRIPTS]
main_script: data/utility/sv_api.lua
main_script: data/utility/sv_util.lua
client_file: data/utility/shared/actions.lua
client_file: data/utility/shared/ai.lua
client_file: data/utility/shared/flags.lua
client_file: data/utility/shared/keys.lua
client_file: data/utility/shared/stats.lua
client_file: data/utility/shared/weapons.lua

[PED_SCRIPTS]
main_script: data/ped/sv_actions.lua		# PED ACTION TREE + NODES
client_script: data/ped/cl_actions.lua
main_script: data/ped/sv_ai.lua				# PED AI TREE + TASKS
client_script: data/ped/cl_ai.lua
main_script: data/ped/sv_attitude.lua		# PED ATTITUDE
client_script: data/ped/cl_attitude.lua
main_script: data/ped/sv_controller.lua		# PED ACTION CONTROLLER (THROTTLE / DIRECTION / ANCHOR)
client_script: data/ped/cl_controller.lua
main_script: data/ped/sv_damage.lua			# PED DAMAGE MULTIPLIERS
client_script: data/ped/cl_damage.lua
main_script: data/ped/sv_emotions.lua		# PED EMOTIONS
client_script: data/ped/cl_emotions.lua
main_script: data/ped/sv_flags.lua			# PED FLAGS
client_script: data/ped/cl_flags.lua
main_script: data/ped/sv_gravity.lua		# PED GRAVITY
client_script: data/ped/cl_gravity.lua
main_script: data/ped/sv_health.lua			# PED HEALTH / DEAD STATE
client_script: data/ped/cl_health.lua
main_script: data/ped/sv_punishment.lua		# PED PUNISHMENT POINTS
client_script: data/ped/cl_punishment.lua
main_script: data/ped/sv_speech.lua			# PED SPEECH
client_script: data/ped/cl_speech.lua
main_script: data/ped/sv_sprint.lua			# PED STAMINA / INFINITE SPRINT
client_script: data/ped/cl_sprint.lua
main_script: data/ped/sv_stats.lua			# PED STATS - AFTER HEALTH GUARANTEES STATS BE APPLIED AFTER REVIVE
client_script: data/ped/cl_stats.lua
main_script: data/ped/sv_target.lua			# PED TARGET
client_script: data/ped/cl_target.lua
main_script: data/ped/sv_weapons.lua		# PED WEAPONS
client_script: data/ped/cl_weapons.lua

[VEHICLE_SCRIPTS]
main_script: data/vehicle/sv_colors.lua		# VEHICLE COLORS
client_script: data/vehicle/cl_colors.lua
main_script: data/vehicle/sv_engine.lua		# VEHICLE ENGINE
client_script: data/vehicle/cl_engine.lua
main_script: data/vehicle/sv_siren.lua		# VEHICLE SIREN
client_script: data/vehicle/cl_siren.lua

[WORLD_SCRIPTS]
main_script: data/world/sv_chapter.lua		# WORLD CHAPTER
client_script: data/world/cl_chapter.lua
main_script: data/world/sv_weather.lua		# WORLD WEATHER
client_script: data/world/cl_weather.lua
main_script: data/world/sv_time.lua			# WORLD TIME
client_script: data/world/cl_time.lua