## timecycle switcher  ##
##        - derpy54320 ##

[PREFERENCES]

# key used to switch timecycles
switch_key: F6

# add PS2 timecycles?
include_ps2: true

# add PC/sb timecycles?
include_pcsb: true

[INFO]
mod_author: Xx_Yubari_xX
mod_help: Allows timecycles to be switched by hitting F3.
require_version: 12

[SCRIPTS]
client_script: main.lua

[FILES]
client_file: DEFAULT/sbtimecycE.dat
client_file: DEFAULT/sbtimecycF.dat
client_file: DEFAULT/sbtimecycS.dat
client_file: DEFAULT/sbtimecycW.dat
client_file: DEFAULT/TIMECYCE.DAT
client_file: DEFAULT/TIMECYCF.DAT
client_file: DEFAULT/TIMECYCS.DAT
client_file: DEFAULT/TIMECYCW.DAT